FROM sconecuratedimages/public-apps:openjdk-11-alpine-scone3.0
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar

RUN which java

RUN SCONE_MODE=sim

RUN SCONE_HEAP=2G SCONE_LOG=7 SCONE_HASH=1 SCONE_ALPINE=1 /usr/bin/java -jar app.jar

RUN mkdir conf/ && scone fspf create fspf.pb

RUN scone --help

ENTRYPOINT ["java","-jar","/app.jar"]
