version: '3'
services:
        demo:
                image: springio/gs-spring-boot-docker
                ports:
                 - "8080:8080"
                command: java -jar /build/libs/demo-0.0.1-SNAPSHOT.jar
                
