FROM sconecuratedimages/public-apps:openjdk-11-alpine-scone3.0
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar

RUN which java

RUN SCONE_MODE=SIM SCONE_HEAP=2G SCONE_LOG=7 SCONE_HASH=1 SCONE_ALPINE=1 && mkdir conf && scone fspf create fspf.pb \
&& scone fspf addr fspf.pb / --not-protected --kernel / \
&& scone fspf addr fspf.pb /tmp/demo/data --encrypted --kernel /tmp/demo/data \
&& scone fspf addf fspf.pb /tmp/demo/data /tmp/demo/data \
&& scone fspf encrypt ./fspf.pb > /conf/keytag 			  \
&& MRENCLAVE="$(SCONE_MODE=SIM SCONE_HEAP=2G SCONE_LOG=7 SCONE_HASH=1 SCONE_ALPINE=1 /usr/bin/java -jar app.jar)"			            \
&& FSPF_TAG=$(cat conf/keytag | awk '{print $9}') 	                    \
&& FSPF_KEY=$(cat conf/keytag | awk '{print $11}')		                \
&& echo "<MRENCLAVE>$MRENCLAVE</MRENCLAVE>"             \
&& echo "<FSPF_KEY>$FSPF_KEY</FSPF_KEY>"			                    \
&& echo "<FSPF_TAG>$FSPF_TAG</FSPF_TAG>"

RUN SCONE_MODE=SIM SCONE_HEAP=2G SCONE_LOG=7 SCONE_HASH=1 SCONE_ALPINE=1 /usr/bin/java -jar app.jar


ENTRYPOINT ["java","-jar","/app.jar"]
