version: '3.4'
services:
  demo:
    image: romainplt/demo
    container_name: demo
    ports:
      - 8080:8080
    devices:
      - /dev/isgx
    volumes:
      - /home/romain/Documents/rest_app/demo/data:/tmp/demo/data:rw
    environment:
      - SCONE_VERSION=1
      - SCONE_LOG=7
      - SCONE_MODE=SIM
      - SCONE_HEAP=2G
      - JAVA_TOOL_OPTIONS=-Xmx64m
    networks:
      - romain-net

volumes:
  demo:
    external: true

networks:
  romain-net:
    external: true
